<?php
/**
 * CloudJobScheduleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Progrupa\Azure;

/**
 * CloudJobScheduleTest Class Doc Comment
 *
 * @category    Class */
// * @description CloudJobSchedule
/**
 * @package     Progrupa\Azure
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CloudJobScheduleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CloudJobSchedule"
     */
    public function testCloudJobSchedule()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

    /**
     * Test attribute "e_tag"
     */
    public function testPropertyETag()
    {

    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {

    }

    /**
     * Test attribute "creation_time"
     */
    public function testPropertyCreationTime()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "state_transition_time"
     */
    public function testPropertyStateTransitionTime()
    {

    }

    /**
     * Test attribute "previous_state"
     */
    public function testPropertyPreviousState()
    {

    }

    /**
     * Test attribute "previous_state_transition_time"
     */
    public function testPropertyPreviousStateTransitionTime()
    {

    }

    /**
     * Test attribute "schedule"
     */
    public function testPropertySchedule()
    {

    }

    /**
     * Test attribute "job_specification"
     */
    public function testPropertyJobSpecification()
    {

    }

    /**
     * Test attribute "execution_info"
     */
    public function testPropertyExecutionInfo()
    {

    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {

    }

    /**
     * Test attribute "stats"
     */
    public function testPropertyStats()
    {

    }

}
