<?php
/**
 * JobReleaseTaskExecutionInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Progrupa\Azure;

/**
 * JobReleaseTaskExecutionInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description JobReleaseTaskExecutionInformation
/**
 * @package     Progrupa\Azure
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JobReleaseTaskExecutionInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "JobReleaseTaskExecutionInformation"
     */
    public function testJobReleaseTaskExecutionInformation()
    {

    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {

    }

    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "task_root_directory"
     */
    public function testPropertyTaskRootDirectory()
    {

    }

    /**
     * Test attribute "task_root_directory_url"
     */
    public function testPropertyTaskRootDirectoryUrl()
    {

    }

    /**
     * Test attribute "exit_code"
     */
    public function testPropertyExitCode()
    {

    }

    /**
     * Test attribute "scheduling_error"
     */
    public function testPropertySchedulingError()
    {

    }

}
