<?php
/**
 * JobUpdateParameterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Progrupa\Azure;

/**
 * JobUpdateParameterTest Class Doc Comment
 *
 * @category    Class */
// * @description JobUpdateParameter
/**
 * @package     Progrupa\Azure
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JobUpdateParameterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "JobUpdateParameter"
     */
    public function testJobUpdateParameter()
    {

    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {

    }

    /**
     * Test attribute "constraints"
     */
    public function testPropertyConstraints()
    {

    }

    /**
     * Test attribute "pool_info"
     */
    public function testPropertyPoolInfo()
    {

    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {

    }

    /**
     * Test attribute "on_all_tasks_complete"
     */
    public function testPropertyOnAllTasksComplete()
    {

    }

}
