<?php
/**
 * PoolAddParameterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Progrupa\Azure;

/**
 * PoolAddParameterTest Class Doc Comment
 *
 * @category    Class */
// * @description PoolAddParameter
/**
 * @package     Progrupa\Azure
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PoolAddParameterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PoolAddParameter"
     */
    public function testPoolAddParameter()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {

    }

    /**
     * Test attribute "vm_size"
     */
    public function testPropertyVmSize()
    {

    }

    /**
     * Test attribute "cloud_service_configuration"
     */
    public function testPropertyCloudServiceConfiguration()
    {

    }

    /**
     * Test attribute "virtual_machine_configuration"
     */
    public function testPropertyVirtualMachineConfiguration()
    {

    }

    /**
     * Test attribute "resize_timeout"
     */
    public function testPropertyResizeTimeout()
    {

    }

    /**
     * Test attribute "target_dedicated"
     */
    public function testPropertyTargetDedicated()
    {

    }

    /**
     * Test attribute "enable_auto_scale"
     */
    public function testPropertyEnableAutoScale()
    {

    }

    /**
     * Test attribute "auto_scale_formula"
     */
    public function testPropertyAutoScaleFormula()
    {

    }

    /**
     * Test attribute "auto_scale_evaluation_interval"
     */
    public function testPropertyAutoScaleEvaluationInterval()
    {

    }

    /**
     * Test attribute "enable_inter_node_communication"
     */
    public function testPropertyEnableInterNodeCommunication()
    {

    }

    /**
     * Test attribute "network_configuration"
     */
    public function testPropertyNetworkConfiguration()
    {

    }

    /**
     * Test attribute "start_task"
     */
    public function testPropertyStartTask()
    {

    }

    /**
     * Test attribute "certificate_references"
     */
    public function testPropertyCertificateReferences()
    {

    }

    /**
     * Test attribute "application_package_references"
     */
    public function testPropertyApplicationPackageReferences()
    {

    }

    /**
     * Test attribute "max_tasks_per_node"
     */
    public function testPropertyMaxTasksPerNode()
    {

    }

    /**
     * Test attribute "task_scheduling_policy"
     */
    public function testPropertyTaskSchedulingPolicy()
    {

    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {

    }

}
