<?php
/**
 * PoolUpdatePropertiesParameterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Progrupa\Azure;

/**
 * PoolUpdatePropertiesParameterTest Class Doc Comment
 *
 * @category    Class */
// * @description PoolUpdatePropertiesParameter
/**
 * @package     Progrupa\Azure
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PoolUpdatePropertiesParameterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PoolUpdatePropertiesParameter"
     */
    public function testPoolUpdatePropertiesParameter()
    {

    }

    /**
     * Test attribute "start_task"
     */
    public function testPropertyStartTask()
    {

    }

    /**
     * Test attribute "certificate_references"
     */
    public function testPropertyCertificateReferences()
    {

    }

    /**
     * Test attribute "application_package_references"
     */
    public function testPropertyApplicationPackageReferences()
    {

    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {

    }

}
