<?php
/**
 * ScheduleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Progrupa\Azure;

/**
 * ScheduleTest Class Doc Comment
 *
 * @category    Class */
// * @description Schedule
/**
 * @package     Progrupa\Azure
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScheduleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Schedule"
     */
    public function testSchedule()
    {

    }

    /**
     * Test attribute "do_not_run_until"
     */
    public function testPropertyDoNotRunUntil()
    {

    }

    /**
     * Test attribute "do_not_run_after"
     */
    public function testPropertyDoNotRunAfter()
    {

    }

    /**
     * Test attribute "start_window"
     */
    public function testPropertyStartWindow()
    {

    }

    /**
     * Test attribute "recurrence_interval"
     */
    public function testPropertyRecurrenceInterval()
    {

    }

}
