<?php
/**
 * TaskIdRangeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Progrupa\Azure;

/**
 * TaskIdRangeTest Class Doc Comment
 *
 * @category    Class */
// * @description The start and end of the range are inclusive. For example, if a range has start 9 and end 12, then it represents tasks &#39;9&#39;, &#39;10&#39;, &#39;11&#39; and &#39;12&#39;.
/**
 * @package     Progrupa\Azure
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaskIdRangeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "TaskIdRange"
     */
    public function testTaskIdRange()
    {

    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {

    }

    /**
     * Test attribute "end"
     */
    public function testPropertyEnd()
    {

    }

}
