<?php
/**
 * CertificatesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Progrupa\Azure;

use \Progrupa\Azure\Configuration;
use \Progrupa\Azure\ApiClient;
use \Progrupa\Azure\ApiException;
use \Progrupa\Azure\ObjectSerializer;

/**
 * CertificatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CertificatesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for certificateAdd
     *
     * Adds a certificate to the specified account..
     *
     */
    public function testCertificateAdd()
    {

    }

    /**
     * Test case for certificateCancelDeletion
     *
     * Cancels a failed deletion of a certificate from the specified account..
     *
     */
    public function testCertificateCancelDeletion()
    {

    }

    /**
     * Test case for certificateDelete
     *
     * Deletes a certificate from the specified account..
     *
     */
    public function testCertificateDelete()
    {

    }

    /**
     * Test case for certificateGet
     *
     * .
     *
     */
    public function testCertificateGet()
    {

    }

    /**
     * Test case for certificateList
     *
     * Lists all of the certificates that have been added to the specified account..
     *
     */
    public function testCertificateList()
    {

    }

}
