<?php
/**
 * ComputeNodesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Progrupa\Azure;

use \Progrupa\Azure\Configuration;
use \Progrupa\Azure\ApiClient;
use \Progrupa\Azure\ApiException;
use \Progrupa\Azure\ObjectSerializer;

/**
 * ComputeNodesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ComputeNodesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for computeNodeAddUser
     *
     * Adds a user account to the specified compute node..
     *
     */
    public function testComputeNodeAddUser()
    {

    }

    /**
     * Test case for computeNodeDeleteUser
     *
     * Deletes a user account from the specified compute node..
     *
     */
    public function testComputeNodeDeleteUser()
    {

    }

    /**
     * Test case for computeNodeDisableScheduling
     *
     * Disables task scheduling on the specified compute node..
     *
     */
    public function testComputeNodeDisableScheduling()
    {

    }

    /**
     * Test case for computeNodeEnableScheduling
     *
     * Enables task scheduling on the specified compute node..
     *
     */
    public function testComputeNodeEnableScheduling()
    {

    }

    /**
     * Test case for computeNodeGet
     *
     * Gets information about the specified compute node..
     *
     */
    public function testComputeNodeGet()
    {

    }

    /**
     * Test case for computeNodeGetRemoteDesktop
     *
     * Gets the Remote Desktop Protocol file for the specified compute node..
     *
     */
    public function testComputeNodeGetRemoteDesktop()
    {

    }

    /**
     * Test case for computeNodeGetRemoteLoginSettings
     *
     * Gets the settings required for remote login to a compute node..
     *
     */
    public function testComputeNodeGetRemoteLoginSettings()
    {

    }

    /**
     * Test case for computeNodeList
     *
     * Lists the compute nodes in the specified pool..
     *
     */
    public function testComputeNodeList()
    {

    }

    /**
     * Test case for computeNodeReboot
     *
     * Restarts the specified compute node..
     *
     */
    public function testComputeNodeReboot()
    {

    }

    /**
     * Test case for computeNodeReimage
     *
     * Reinstalls the operating system on the specified compute node..
     *
     */
    public function testComputeNodeReimage()
    {

    }

    /**
     * Test case for computeNodeUpdateUser
     *
     * Updates the password or expiration time of a user account on the specified compute node..
     *
     */
    public function testComputeNodeUpdateUser()
    {

    }

    /**
     * Test case for poolRemoveNodes
     *
     * Removes compute nodes from the specified pool..
     *
     */
    public function testPoolRemoveNodes()
    {

    }

}
