<?php
/**
 * JobSchedulesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Progrupa\Azure;

use \Progrupa\Azure\Configuration;
use \Progrupa\Azure\ApiClient;
use \Progrupa\Azure\ApiException;
use \Progrupa\Azure\ObjectSerializer;

/**
 * JobSchedulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JobSchedulesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for jobScheduleAdd
     *
     * Adds a job schedule to the specified account..
     *
     */
    public function testJobScheduleAdd()
    {

    }

    /**
     * Test case for jobScheduleDelete
     *
     * Deletes a job schedule from the specified account..
     *
     */
    public function testJobScheduleDelete()
    {

    }

    /**
     * Test case for jobScheduleDisable
     *
     * Disables a job schedule..
     *
     */
    public function testJobScheduleDisable()
    {

    }

    /**
     * Test case for jobScheduleEnable
     *
     * Enables a job schedule..
     *
     */
    public function testJobScheduleEnable()
    {

    }

    /**
     * Test case for jobScheduleExists
     *
     * Checks the specified job schedule exists..
     *
     */
    public function testJobScheduleExists()
    {

    }

    /**
     * Test case for jobScheduleGet
     *
     * .
     *
     */
    public function testJobScheduleGet()
    {

    }

    /**
     * Test case for jobScheduleList
     *
     * Lists all of the job schedules in the specified account..
     *
     */
    public function testJobScheduleList()
    {

    }

    /**
     * Test case for jobSchedulePatch
     *
     * Updates the properties of the specified job schedule..
     *
     */
    public function testJobSchedulePatch()
    {

    }

    /**
     * Test case for jobScheduleTerminate
     *
     * Terminates a job schedule..
     *
     */
    public function testJobScheduleTerminate()
    {

    }

    /**
     * Test case for jobScheduleUpdate
     *
     * Updates the properties of the specified job schedule..
     *
     */
    public function testJobScheduleUpdate()
    {

    }

}
