<?php
/**
 * JobsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Progrupa\Azure;

use \Progrupa\Azure\Configuration;
use \Progrupa\Azure\ApiClient;
use \Progrupa\Azure\ApiException;
use \Progrupa\Azure\ObjectSerializer;

/**
 * JobsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JobsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for jobAdd
     *
     * Adds a job to the specified account..
     *
     */
    public function testJobAdd()
    {

    }

    /**
     * Test case for jobDelete
     *
     * Deletes a job..
     *
     */
    public function testJobDelete()
    {

    }

    /**
     * Test case for jobDisable
     *
     * Disables the specified job, preventing new tasks from running..
     *
     */
    public function testJobDisable()
    {

    }

    /**
     * Test case for jobEnable
     *
     * Enables the specified job, allowing new tasks to run..
     *
     */
    public function testJobEnable()
    {

    }

    /**
     * Test case for jobGet
     *
     * Gets information about the specified job..
     *
     */
    public function testJobGet()
    {

    }

    /**
     * Test case for jobGetAllJobsLifetimeStatistics
     *
     * Gets lifetime summary statistics for all of the jobs in the specified account..
     *
     */
    public function testJobGetAllJobsLifetimeStatistics()
    {

    }

    /**
     * Test case for jobList
     *
     * Lists all of the jobs in the specified account..
     *
     */
    public function testJobList()
    {

    }

    /**
     * Test case for jobListFromJobSchedule
     *
     * Lists the jobs that have been created under the specified job schedule..
     *
     */
    public function testJobListFromJobSchedule()
    {

    }

    /**
     * Test case for jobListPreparationAndReleaseTaskStatus
     *
     * Lists the execution status of the Job Preparation and Job Release task for the specified job across the compute nodes where the job has run..
     *
     */
    public function testJobListPreparationAndReleaseTaskStatus()
    {

    }

    /**
     * Test case for jobPatch
     *
     * Updates the properties of the specified job..
     *
     */
    public function testJobPatch()
    {

    }

    /**
     * Test case for jobTerminate
     *
     * Terminates the specified job, marking it as completed..
     *
     */
    public function testJobTerminate()
    {

    }

    /**
     * Test case for jobUpdate
     *
     * Updates the properties of the specified job..
     *
     */
    public function testJobUpdate()
    {

    }

}
