<?php
/**
 * PoolsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Progrupa\Azure;

use \Progrupa\Azure\Configuration;
use \Progrupa\Azure\ApiClient;
use \Progrupa\Azure\ApiException;
use \Progrupa\Azure\ObjectSerializer;

/**
 * PoolsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PoolsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for poolAdd
     *
     * Adds a pool to the specified account..
     *
     */
    public function testPoolAdd()
    {

    }

    /**
     * Test case for poolDelete
     *
     * Deletes a pool from the specified account..
     *
     */
    public function testPoolDelete()
    {

    }

    /**
     * Test case for poolDisableAutoScale
     *
     * Disables automatic scaling for a pool..
     *
     */
    public function testPoolDisableAutoScale()
    {

    }

    /**
     * Test case for poolEnableAutoScale
     *
     * Enables automatic scaling for a pool..
     *
     */
    public function testPoolEnableAutoScale()
    {

    }

    /**
     * Test case for poolEvaluateAutoScale
     *
     * Gets the result of evaluating an automatic scaling formula on the pool..
     *
     */
    public function testPoolEvaluateAutoScale()
    {

    }

    /**
     * Test case for poolExists
     *
     * .
     *
     */
    public function testPoolExists()
    {

    }

    /**
     * Test case for poolGet
     *
     * .
     *
     */
    public function testPoolGet()
    {

    }

    /**
     * Test case for poolGetAllPoolsLifetimeStatistics
     *
     * Gets lifetime summary statistics for all of the pools in the specified account..
     *
     */
    public function testPoolGetAllPoolsLifetimeStatistics()
    {

    }

    /**
     * Test case for poolList
     *
     * Lists all of the pools in the specified account..
     *
     */
    public function testPoolList()
    {

    }

    /**
     * Test case for poolListPoolUsageMetrics
     *
     * Lists the usage metrics, aggregated by pool across individual time intervals, for the specified account..
     *
     */
    public function testPoolListPoolUsageMetrics()
    {

    }

    /**
     * Test case for poolPatch
     *
     * Updates the properties of the specified pool..
     *
     */
    public function testPoolPatch()
    {

    }

    /**
     * Test case for poolResize
     *
     * Changes the number of compute nodes that are assigned to a pool..
     *
     */
    public function testPoolResize()
    {

    }

    /**
     * Test case for poolStopResize
     *
     * Stops an ongoing resize operation on the pool..
     *
     */
    public function testPoolStopResize()
    {

    }

    /**
     * Test case for poolUpdateProperties
     *
     * Updates the properties of the specified pool..
     *
     */
    public function testPoolUpdateProperties()
    {

    }

    /**
     * Test case for poolUpgradeOS
     *
     * Upgrades the operating system of the specified pool..
     *
     */
    public function testPoolUpgradeOS()
    {

    }

}
