<?php
/**
 * TasksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BatchService
 *
 * A client for issuing REST requests to the Azure Batch service.
 *
 * OpenAPI spec version: 2016-07-01.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Progrupa\Azure;

use \Progrupa\Azure\Configuration;
use \Progrupa\Azure\ApiClient;
use \Progrupa\Azure\ApiException;
use \Progrupa\Azure\ObjectSerializer;

/**
 * TasksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Progrupa\Azure
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TasksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for taskAdd
     *
     * Adds a task to the specified job..
     *
     */
    public function testTaskAdd()
    {

    }

    /**
     * Test case for taskAddCollection
     *
     * Adds a collection of tasks to the specified job..
     *
     */
    public function testTaskAddCollection()
    {

    }

    /**
     * Test case for taskDelete
     *
     * Deletes a task from the specified job..
     *
     */
    public function testTaskDelete()
    {

    }

    /**
     * Test case for taskGet
     *
     * Gets information about the specified task..
     *
     */
    public function testTaskGet()
    {

    }

    /**
     * Test case for taskList
     *
     * Lists all of the tasks that are associated with the specified job..
     *
     */
    public function testTaskList()
    {

    }

    /**
     * Test case for taskListSubtasks
     *
     * Lists all of the subtasks that are associated with the specified multi-instance task..
     *
     */
    public function testTaskListSubtasks()
    {

    }

    /**
     * Test case for taskReactivate
     *
     * Reactivates the specified task..
     *
     */
    public function testTaskReactivate()
    {

    }

    /**
     * Test case for taskTerminate
     *
     * Terminates the specified task..
     *
     */
    public function testTaskTerminate()
    {

    }

    /**
     * Test case for taskUpdate
     *
     * .
     *
     */
    public function testTaskUpdate()
    {

    }

}
